unlocking the user if the password is reset successfully
scandipwa/customer-graph-ql pull request #37
Opened 2022-06-21 17:30 UTC by AzizKHAN030

**Related issue(s):**
* Fixes scandipwa/scandipwa#4727

**Problem:**
* User couldn't access the account even by resetting the password after being locked

**In this PR:**
* Added function that unlocks the user, and calling it if the password reset successfully

2022-06-22 12:36 UTC, AzizKHAN030 commented
PR can be tested on [https://scandipwapmrevprtest-dev.indvp.com/](https://scandipwapmrevprtest-dev.indvp.com/)

2022-06-23 14:56 UTC, Elena-Evsa commented
Fixed

2022-06-23 18:26 UTC, zans-laksa requested changes

2022-06-23 18:26 UTC, zans-laksa commented on src/Model/Resolver/ResetPassword.php
> +
Please add dependencies in the class constructor.
See the example from the constructor of this class.

2022-06-24 11:05 UTC, zans-laksa approved these changes

2022-06-24 17:32 UTC, merged